//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 设置 {
            get {
                return ((string)(this["设置"]));
            }
            set {
                this["设置"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\robert\\Pictures\\Screenshots\\Screenshot 2024-03-19 010206.png")]
        public string 图像位置_原aruco {
            get {
                return ((string)(this["图像位置_原aruco"]));
            }
            set {
                this["图像位置_原aruco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\robert\\Desktop\\复试面试.txt")]
        public string log文件保存位置 {
            get {
                return ((string)(this["log文件保存位置"]));
            }
            set {
                this["log文件保存位置"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\5graduateproject\\5.2re\\test3\\pyCalibration\\data\\240415\\captured\\position_00a")]
        public string gray图片文件夹 {
            get {
                return ((string)(this["gray图片文件夹"]));
            }
            set {
                this["gray图片文件夹"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public int camsizew {
            get {
                return ((int)(this["camsizew"]));
            }
            set {
                this["camsizew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int camsizeh {
            get {
                return ((int)(this["camsizeh"]));
            }
            set {
                this["camsizeh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public int prosizew {
            get {
                return ((int)(this["prosizew"]));
            }
            set {
                this["prosizew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int prosizeh {
            get {
                return ((int)(this["prosizeh"]));
            }
            set {
                this["prosizeh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public string 预投影画面长度 {
            get {
                return ((string)(this["预投影画面长度"]));
            }
            set {
                this["预投影画面长度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public string 预投影画面高度 {
            get {
                return ((string)(this["预投影画面高度"]));
            }
            set {
                this["预投影画面高度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\robert\\Pictures\\Camera Roll\\WIN_20240312_16_03_37_Pro.jpg")]
        public string 内接矩形图片 {
            get {
                return ((string)(this["内接矩形图片"]));
            }
            set {
                this["内接矩形图片"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string 投影机个数 {
            get {
                return ((string)(this["投影机个数"]));
            }
            set {
                this["投影机个数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int 横向位置个数 {
            get {
                return ((int)(this["横向位置个数"]));
            }
            set {
                this["横向位置个数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int 纵向位置个数 {
            get {
                return ((int)(this["纵向位置个数"]));
            }
            set {
                this["纵向位置个数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\robert\\Desktop\\data.txt")]
        public string 锚点保存位置 {
            get {
                return ((string)(this["锚点保存位置"]));
            }
            set {
                this["锚点保存位置"] = value;
            }
        }
    }
}
